project:
  type: website

website:
  title: "金"
  site-url: https://santidu.github.io
  description: "This is Jin's personal Blog."
  navbar:
    right:
      - text: Blog
        href: blog.qmd
format:
  html:
    theme: flatly
    css: styles.css

editor: visual

