project:
  type: website

website:
  title: "金"
  site-url: https://santidu.github.io
  description: "This is Jin's personal Blog."
  navbar:
    right:
      - text: Blog
        href: blog.qmd
      - icon: instagram
        href: https://www.instagram.com/santi_du
      - icon: github
        href: https://github.com/SantiDu
      - icon: linkedin
        href: https://www.linkedin.com/in/santidu
format:
  html:
    theme: lux
    css: styles.css

editor: visual

